// Code generated by BuilderGen v0.0.7
package cmd

type ConfigBuilder struct {
	Source      string
	Destination string
	Package     string
	Name        string
}

func NewConfigBuilder(b *Config) *ConfigBuilder {
	if b == nil {
		return nil
	}

	return &ConfigBuilder{
		Source:      b.Source,
		Destination: b.Destination,
		Package:     b.Package,
		Name:        b.Name,
	}
}

func (b *ConfigBuilder) WithSource(source string) *ConfigBuilder {
	b.Source = source
	return b
}

func (b *ConfigBuilder) WithDestination(destination string) *ConfigBuilder {
	b.Destination = destination
	return b
}

func (b *ConfigBuilder) WithPackage(package_ string) *ConfigBuilder {
	b.Package = package_
	return b
}

func (b *ConfigBuilder) WithName(name string) *ConfigBuilder {
	b.Name = name
	return b
}

func (b *ConfigBuilder) Build() *Config {
	return &Config{
		Source:      b.Source,
		Destination: b.Destination,
		Package:     b.Package,
		Name:        b.Name,
	}
}
