package consts

const (
	PARAM_NAME = "BuilderGen"
	VERSION    = "v0.0.5"

	DEFAULT_BUILDER_SUFFIX = "_builder.go"

	BUILD_HEADER  = "// Code generated by " + PARAM_NAME + " " + VERSION
	BUILD_PACKAGE = "package"
)
